// This file was auto-generated by prisma-generator-typescript-interfaces

export interface Brand {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  products?: Product[];
}

export interface Building {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  zones?: Zone[];
}

export interface Category {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  products?: Product[];
}

export interface Item {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  storage_location_id: number | null;
  product_status_id: number | null;
  product_id: number;
  description: string | null;
  barcode_number: number | null;
  product?: Product;
  product_status?: ProductStatus | null;
  storage_location?: StorageLocation | null;
  item_in_loans?: ItemInLoan[];
}

export interface ItemInLoan {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  returned_at: Date | null;
  loan_id: number;
  item_id: number;
  with_bag: boolean;
  with_lock: boolean;
  item?: Item;
  loan?: Loan;
}

export interface Loan {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  date_of_return: Date | null;
  location_of_use_id: number | null;
  user_id: number;
  helpdesk_personel_id: number | null;
  selfservice_case_id: number | null;
  recipient_type_id: number | null;
  loan_length: number | null;
  mail_sent: boolean;
  items_in_loan?: ItemInLoan[];
  personnel?: User | null;
  zone?: Zone | null;
  recipient_type?: RecipientType | null;
  loaner?: User;
}

export interface PickupLocation {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
}

export interface ProductStatus {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  items?: Item[];
}

export interface Product {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  brand_id: number;
  category_id: number;
  product_id_prefix: string | null;
  image_name: string | null;
  items?: Item[];
  category?: Category;
  brand?: Brand;
}

export interface RecipientType {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  loans?: Loan[];
}

export interface StorageLocation {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  zone_id: number;
  kabinet: string | null;
  shelf: string | null;
  idle_since: Date | null;
  img_name: string | null;
  items?: Item[];
}

export interface User {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  username: string;
  loans_managed?: Loan[];
  loans?: Loan[];
}

export interface Zone {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  name: string;
  building_id: number;
  floor_level: number;
  loans?: Loan[];
  building?: Building;
}

export interface Feedback {
  id: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  title: string;
  description: string;
}
