name: sop-udlaanssystem
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend/udlånssystem
      dockerfile: Dockerfile
      target: prod
    env_file:
      - frontend/udlånssystem/.env
    networks:
      - internal

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    env_file:
      - backend/.env
      - backend/.docker.env
    networks:
      - internal

  db:
    container_name: db
    image: mariadb:10.5
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    env_file:
      - backend/.docker.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - public
      - internal

  nginx:
    container_name: nginx
    image: nginx:1.19.6
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - public
      - internal

  ldap:
    container_name: ldap
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    env_file:
      - backend/.docker.env
    command: --copy-service
    volumes:
      - ./backend/ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    networks:
      - public
      - internal

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
    ports:
      - "6443:443"
    depends_on:
      - ldap
    networks:
      - public
      - internal

networks:
  public:
    driver: bridge
  internal:
    name: internal
    internal: true
  
volumes:
  db:
    driver: local
