# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:


    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Delete old backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        script: |
          rm -rf /home/lager/backend

    - name: Deploy backend to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        source: "backend/*" # Update this with the path to your build directory
        target: "/home/lager/backend" # Update this with the target path on your server
        strip_components: 1

    - name: Stop running backend
      continue-on-error: true
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/lager/backend
          pm2 delete index.js

    - name: Install nodejs packages
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/lager/backend
          npm install

    - name: Copy env file
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/lager
          cp .env /home/lager/backend/.env

    - name: Start backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_NAME }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port:  ${{ secrets.SERVER_SSH_PORT }}
        script: |
          cd /home/lager/backend
          npm run build
