name: Deploy Docker

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # So far, only the backend is being deployed via Docker

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if running in act
        id: is_act
        run: |
          if [ "$ACT" = "true" ]; then
            echo "act=true" >> "$GITHUB_OUTPUT"
          else
            echo "act=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Build Docker image
        run: docker build -t sop-backend:latest ./backend

      - name: Save Docker image as tar
        run: docker save sop-backend:latest -o backend.tar

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: "backend.tar"
          target: "~/"
        if: steps.is_act.outputs.act == 'false'

      - name: Load and run Docker image on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            docker load -i ~/backend.tar
            docker stop sop-backend || true && docker rm sop-backend || true
            docker run -d --name sop-backend -p 3000:3000 sop-backend:latest
        if: steps.is_act.outputs.act == 'false'
