name: Deploy Docker

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # So far, only the backend is being deployed via Docker

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check if running in act
        id: is_act
        run: |
          if [ "$ACT" = "true" ]; then
            echo "act=true" >> "$GITHUB_OUTPUT"
          else
            echo "act=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy via SSH
        if: steps.is_act.outputs.act == 'false'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd /home/lager/sop-it-service-solution
            git pull origin main
            docker system prune -f
            npm run docker:prod
