name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    name: Test SSH to Server
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH key format
        run: |
          echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > temp_key
          chmod 600 temp_key
          ssh-keygen -lf temp_key || echo "❌ Couldn't read private key"

      - name: Attempt SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: echo "✅ SSH connection successful"
