name: Deploy Frontend (Student View)

on:
  push:
    branches:
      - main
    paths:
      - "frontend/student-view"
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/student-view

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if running in act
        id: is_act
        run: |
          if [ "$ACT" = "true" ]; then
            echo "act=true" >> "$GITHUB_OUTPUT"
          else
            echo "act=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Deploy to server
        if: steps.is_act.outputs.act == 'false'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "frontend/student-view/dist/*"
          target: "/var/www/lager/student-view/"
          rm: true
          strip_components: 3 #remove frontend/student-view/dist when copying to /var/www/lager/
